events {}
http {
    server {
        listen 80;

        location /download {
            proxy_pass http://api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # Disable buffering to allow streaming
            proxy_buffering off;
        }

        location /health {
            proxy_pass http://api:8080/health;
            access_log off;
        }
    }
}
